### PR TITLE
OAK-9136: Allow elasticsearch port to be read from secrets

### PR DESCRIPTION
**Pull request by averma21**
* Reading port as a String instead of Integer as the values provided for interpolation are Strings

### CODE REVIEW

**Review by fabriziofortino — COMMENTED** [review]
Before changing this, have you tried to remove the `quote` function the helm chart?

**Comment by averma21** [comment]
I didn't try this in k8s environment. I directly tried on a local environment by setting the value of
`org.apache.felix.configadmin.plugin.interpolation.secretsdir` in `sling.properties` file. 

I did some debugging and here are the findings - 

The value we specify in OSGI configuration for reading from secrets is `$[secret:elasticsearch/port]` - which is a string. This string gets replaced by actual value by [InterpolationConfigurationPlugin](https://github.com/apache/felix-dev/blob/9bd66812f21944925268bfd5551218c436886d30/configadmin-plugins/interpolation/src/main/java/org/apache/felix/configadmin/plugin/interpolation/InterpolationConfigurationPlugin.java#L119). However if we specify that the property type is integer (by using `intValue` in the `@Property` annotation in `ElasticIndexProviderService`), the string `$[secret:elasticsearch/port]` never reaches `InterpolationConfigurationPlugin`. This is because `ConfigurationAdmin` tries to convert `$[secret:elasticsearch/port]` to an integer [here](https://github.com/apache/felix-dev/blob/9bd66812f21944925268bfd5551218c436886d30/webconsole/src/main/java/org/apache/felix/webconsole/internal/configuration/ConfigAdminSupport.java#L240) and it fails.

**Comment by fabriziofortino** [comment]
@averma21 I asked because I have seen `ìntValue`(s) used a lot in the codebase (see `LuceneIndexProviderService` as an example).

**Comment by averma21** [comment]
@fabriziofortino using `intValue` is not a problem. In fact it should be used whenever we want to read an integer. However, I think due to the mechanism by which felix configAdmin and interpolation works, we can't use intValue in any property which depends on interpolation.

The code breaks at a point before it has even gone to read the value of port from secret file. So I think the value in secret file doesn't matter in this case. The code breaks while converting the string  `$[secret:elasticsearch/port]` to integer. It is not breaking while converting the value present in the secret file to integer. It doesn't even reach that point.

However I am trying this on a k8s deployment and just to be 100% sure I will even try what you suggested :)

**Comment by averma21** [comment]
I checked on k8s with an old image (which doesn't contain fix of this PR) and I changed author's secret to not `quote` the port value from values file. However it didn't solve the issue.
I didn't remove the `quote` on publish and I checked the difference in the secret file that is created on both of them. There was no difference. Using cat to view the file showed just `9200` at both places. 

I also tested the solution in this PR and this is solves the issue.

**Review by thomasmueller — APPROVED** [review]

**Pull request closed without merging**
